catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages: []

catalog:

catalogs:
  build:
    '@nuxt/content': ^3.10.0
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/kit': ^4.2.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.12
    '@unocss/nuxt': ^66.5.12
    '@vite-pwa/nuxt': ^1.1.0
    '@vueuse/nuxt': ^14.1.0
    changelogen: ^0.6.2
    changelogithub: ^14.0.0
    nuxt: ^4.2.2
    unocss: ^66.5.12
    unplugin: ^2.3.10
    vite: ^7.1.12
  dev:
    '@antfu/eslint-config': ^6.7.3
    eslint: ^9.39.2
    eslint-plugin-format: ^1.2.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.2
    zx: ^8.8.5
  frontend:
    '@vueuse/core': ^14.1.0
    markdown-it: ^14.1.0
    pinia: ^3.0.4
    plotly.js-dist-min: ^3.3.1
    vue: ^3.5.26
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/lucide': ^1.2.82
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/radix-icons': ^1.2.6
    '@iconify-json/tabler': ^1.2.26
    '@iconify-json/twemoji': ^1.2.5
  types:
    '@types/markdown-it': ^14.1.2
    '@types/node': ^25.0.3
    '@types/plotly.js-dist-min': ^2.3.4

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
